#!/usr/bin/env python3
"""
XForge Knowledge Search — Hybrid semantic + keyword search CLI.

Usage:
    python .xforge/scripts/search.py "query" [--top 10] [--json]

Requirements:
    - .xforge/knowledge/embeddings.json (generated by index-knowledge.py)
    - Python 3.11+
"""

import json
import math
import re
import sys
import os
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent.parent
EMBEDDINGS_FILE = ROOT / ".xforge" / "knowledge" / "embeddings.json"
INDEX_FILE = ROOT / ".xforge" / "knowledge" / "INDEX.json"


def log(msg: str):
    print(f"[search] {msg}", file=sys.stderr)


def cosine_similarity(a: list[float], b: list[float]) -> float:
    """Calculate cosine similarity between two vectors."""
    if len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def keyword_score(query: str, text: str) -> float:
    """Calculate keyword match score."""
    query_terms = query.lower().split()
    text_lower = text.lower()
    if not query_terms or not text_lower:
        return 0.0
    score = 0
    for term in query_terms:
        if len(term) < 2:
            continue
        count = text_lower.count(term)
        score += count / max(len(text_lower), 1)
    return min(score * 100, 1.0)


def load_embeddings() -> list[dict]:
    """Load embeddings from file."""
    if not EMBEDDINGS_FILE.exists():
        log("No embeddings file found. Run index-knowledge.py first.")
        return []
    return json.loads(EMBEDDINGS_FILE.read_text(encoding="utf-8"))


def load_index() -> dict:
    """Load knowledge index."""
    if not INDEX_FILE.exists():
        return {"entries": []}
    return json.loads(INDEX_FILE.read_text(encoding="utf-8"))


def search(query: str, top_k: int = 10, semantic_weight: float = 0.6) -> list[dict]:
    """Search knowledge using hybrid semantic + keyword matching."""
    embeddings = load_embeddings()
    index = load_index()
    index_map = {e.get("id"): e for e in index.get("entries", [])}

    if not embeddings:
        log("No embeddings available. Falling back to keyword search only.")
        results = []
        query_lower = query.lower()
        for entry in index.get("entries", []):
            text = f"{entry.get('title', '')} {entry.get('summary', '')} {' '.join(entry.get('tags', []))}"
            score = keyword_score(query, text)
            if score > 0:
                results.append({
                    "id": entry.get("id", ""),
                    "title": entry.get("title", ""),
                    "path": entry.get("path", ""),
                    "score": score,
                    "matchType": "keyword"
                })
        return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

    # Generate query embedding (hash-based fallback)
    import hashlib
    hash_val = int(hashlib.md5(query.encode()).hexdigest(), 16)
    query_vector = []
    for i in range(len(embeddings[0]["vector"])):
        query_vector.append(math.sin(hash_val + i) * 0.5)
    norm = math.sqrt(sum(v * v for v in query_vector))
    if norm > 0:
        query_vector = [v / norm for v in query_vector]

    results = []
    for emb in embeddings:
        sem_score = cosine_similarity(query_vector, emb["vector"])
        metadata = emb.get("metadata", {})
        text = f"{metadata.get('title', '')} {metadata.get('path', '')} {' '.join(metadata.get('tags', []))}"
        key_score = keyword_score(query, text)

        combined = (sem_score * semantic_weight) + (key_score * (1 - semantic_weight))

        if combined > 0.01:
            results.append({
                "id": emb["id"],
                "title": metadata.get("title", ""),
                "path": metadata.get("path", ""),
                "domain": metadata.get("domain", ""),
                "tags": metadata.get("tags", []),
                "score": round(combined, 4),
                "semanticScore": round(sem_score, 4),
                "keywordScore": round(key_score, 4),
                "matchType": "hybrid" if sem_score > 0.1 and key_score > 0.01 else ("semantic" if sem_score > 0.1 else "keyword")
            })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Search XForge knowledge")
    parser.add_argument("query", help="Search query")
    parser.add_argument("--top", type=int, default=10, help="Number of results")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    results = search(args.query, args.top)

    if args.json:
        print(json.dumps(results, indent=2))
    else:
        if not results:
            print("No results found.")
            return
        print(f"Found {len(results)} results for '{args.query}':\n")
        for i, r in enumerate(results, 1):
            print(f"  {i}. [{r['matchType']}] {r.get('title', r['id'])}")
            print(f"     Path: {r.get('path', 'N/A')}")
            print(f"     Score: {r['score']:.4f}")
            if r.get('domain'):
                print(f"     Domain: {r['domain']}")
            print()


if __name__ == "__main__":
    main()
