const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', 'ref', 'icones', 'svg');
const outFile = path.join(__dirname, '..', 'src', 'webview', 'icons.ts');

const needed = {
  chevron: 'chevron-down.svg',
  send: 'paper-plane-top.svg',
  plus: 'square-plus.svg',
  history: 'clock.svg',
  trash: 'trash-can.svg',
  list: 'list.svg',
  arrowRight: 'arrow-right.svg',
  x: 'xmark-large.svg',
  down: 'down-long.svg',
  user: 'user.svg',
  code: 'code.svg',
};

const out = [];
out.push('// AUTO-GENERATED by scripts/build-icons.ts do not edit');
out.push('// Source: ref/icones/svg/ (Font Awesome Pro 7.1.0)');
out.push('');

const used = [];
for (const [name, file] of Object.entries(needed)) {
  const fp = path.join(root, file);
  if (!fs.existsSync(fp)) {
    console.error('NAO EXISTE:', fp);
    continue;
  }
  let content = fs.readFileSync(fp, 'utf-8')
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/<!--.*?-->/g, '')
    .trim();
  out.push('export const ICON_' + name.toUpperCase() + " = `" + content + "`;");
  used.push(name);
}

out.push('');
out.push('export function icon(name: string, size = 14): string {');
out.push('  const map: Record<string, string> = {');
for (const u of used) {
  out.push("    '" + u + "': ICON_" + u.toUpperCase() + ",");
}
out.push('  };');
out.push("  const inner = map[name] || '';");
out.push("  return `<svg width='${size}' height='${size}' viewBox='0 0 512 512' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>${inner}</svg>`;");
out.push('}');

fs.writeFileSync(outFile, out.join('\n'), 'utf-8');
console.log('OK', used.length, 'icons ->', outFile);
